#!/bin/bash

function isInstalled {
	if [ 1 -eq "$(dpkg -l | grep -c $1)" ] 
		then 
			pkdgInstalled=true
			echo "	*** $1 is already installed. Skip installation ***	"
		else 
			pkdgInstalled=false
	fi
}

echo '	***	*** Install developers tools start ***'


echo '	*** *** Add repositories'
# java oracle
add-apt-repository -y ppa:webupd8team/java 
# sublime
add-apt-repository -y ppa:webupd8team/sublime-text-3 
# update
apt-get -y update 

echo '	*** Install oracle JDK 7, 8'
apt-get -y install oracle-java7-installer
apt-get -y install oracle-java8-installer

echo '	*** Install groovy 2.3.7'
wget /opt http://dl.bintray.com/groovy/maven/groovy-src-2.3.7.zip
unzip /opt/groovy-src-2.3.7.zip
mv /opt/groovy-src-2.3.7 /opt/groovy
echo -e "\n export GROOVY_HOME=/opt/groovy" >> ~/.profile

echo '	*** Install Git and giggle'
apt-get -y install git giggle

echo '	*** Install Svn'
apt-get -y install subversion

echo '	*** Install Sublime text 3'
apt-get -y install sublime-text-installer

echo '	*** Install gradle'
wget -P /opt https://services.gradle.org/distributions/gradle-2.1-all.zip
unzip /opt/gradle-2.1-all.zip -d /opt
mv /opt/gradle-2.1 /opt/gradle
echo -e "\n export GRADLE_HOME=/opt/gradle" >> ~/.profile

echo '	*** Install rdesktop'
isInstalled rdesktop
[ "$pkdgInstalled" == 'false' ] && apt-get -y install rdesktop

echo '	*** Install openVpn'
isInstalled openvpn
[ "$pkdgInstalled" == 'false' ] && apt-get -y install openvpn

# dir for my bash and groovy scripts
mkdir /opt/myscript
# add all path (groovy, gradle, idea, myscript)
echo -e "\n export PATH=$PATH:$GROOVY_HOME/bin:$GRADLE_HOME/bin:/opt/idea/bin:/opt/myscript" >> ~/.profile

# echo '	*** Install gyazo
# apt-get -y install ruby imagemagick
# wget https://github.com/downloads/kambara/Gyazo-for-Linux/gyazo_1.0-1_all.deb -P /opt
# dpkg -i /opt/gyazo_1.0-1_all.deb
# sed -i.bak s/gyazo.com/screenshot.haulmont.com/g /usr/bin/gyazo
# sed -i.bak s/upload.cgi/upload.php/g /usr/bin/gyazo

echo '	*** Revert old subersionn version to ubuntu 14 ****	'
sudo sh -c "echo '\ndeb http://us.archive.ubuntu.com/ubuntu precise main' >> /etc/apt/sources.list"
apt-get -y -t precise install libsvn1 subversion
apt-mark hold libsvn1 subversion

echo '	*** make sublime text default editor'
sed -i.bak s/gedit.desktop/sublime_text.desktop/g /usr/share/applications/defaults.list

apt-get -y autoremove